### PR TITLE
update storage class

### PR DESCRIPTION
**Pull request by shashanksinha89**

### CODE REVIEW

**Review by mpigram — COMMENTED** [review]
I've left some comments - please answer when you get a chance and then I'm happy to merge to Dev.

I can then work on getting the charts added into our deployment

**Comment by himanshu2464** [comment]
> Has the slack notifier been removed? I thought we had a channel setup that we were using?

yes, it is removed, you can check it.

**Comment by himanshu2464** [comment]
> So I take it you aren't using Nginx for the ingress? Just the AKS LB? Not an issue, I just noticed you changed it from `type: ClusterIP` to `type:LoadBalancer`

yes because we are not using Nginx as ingress, instead we are using azure AKS LB. with giving DNS lable to load balancer.

**Comment by himanshu2464** [comment]
> Are you just returning this to default settings or was our internal IP's removed?

yes this is the default setting and the internal IP of the VPN is removed because it should be exposed and if needed we can add internal Ip during deployment, with a set parameter of loadBalancerSourceRanges.

**Comment by mpigram** [comment]
OK thanks Himanshu - I'll merge to Develop and then I'll look to add to our deployment code today.

**Pull request merged**
